apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: getorgi
        image: achujozef0709/getorgi:latest
        ports:
        - containerPort: 8000 
